const mockData = [{
  "id": 1,
  "label": "n/a",
  "type": "Number",
  "active": true,
  "sfObject": "Account",
  "sfField": "methodical",
  "clauseLabel": "Adaptive optimizing benchmark",
  "clauseValue": "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
  "clauseActive": true,
  "clauseObject": "Account",
  "clauseField": "Victor Sierra",
  "created": "2020-11-07T12:04:52Z"
}, {
  "id": 2,
  "label": "Finance",
  "type": "Number",
  "active": true,
  "sfObject": "Account",
  "sfField": "Public-key",
  "clauseLabel": "Pre-emptive exuding implementation",
  "clauseValue": "Nulla facilisi. Cras non velit nec nisi vulputate nonummy.",
  "clauseActive": false,
  "clauseObject": "Contract",
  "clauseField": "Papa",
  "created": "2020-10-06T12:38:19Z"
}, {
  "id": 3,
  "label": "Consumer Services",
  "type": "Boolean",
  "active": true,
  "sfObject": "Lead",
  "sfField": "strategy",
  "clauseLabel": "Synergized fresh-thinking challenge",
  "clauseValue": "Nulla mollis molestie lorem.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Sierra X-ray Lima",
  "created": "2020-10-08T00:37:43Z"
}, {
  "id": 4,
  "label": "n/a",
  "type": "Number",
  "active": true,
  "sfObject": "Custom Obj 1",
  "sfField": "Graphical User Interface",
  "clauseLabel": "Synchronised bandwidth-monitored process improvement",
  "clauseValue": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Alfa Kilo",
  "created": "2020-10-17T05:17:57Z"
}, {
  "id": 5,
  "label": "Finance",
  "type": "Multiselect",
  "active": false,
  "sfObject": "Contract",
  "sfField": "challenge",
  "clauseLabel": "Optimized systematic capacity",
  "clauseValue": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Golf Juliett",
  "created": "2020-10-16T23:23:28Z"
}, {
  "id": 6,
  "label": "Consumer Services",
  "type": "Single Select",
  "active": true,
  "sfObject": "Contract",
  "sfField": "leading edge",
  "clauseLabel": "Configurable encompassing Graphical User Interface",
  "clauseValue": "Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
  "clauseActive": false,
  "clauseObject": "Contract",
  "clauseField": "India Golf",
  "created": "2020-10-13T05:24:13Z"
}, {
  "id": 7,
  "label": "Health Care",
  "type": "Single Select",
  "active": false,
  "sfObject": "Custom Obj 1",
  "sfField": "strategy",
  "clauseLabel": "Monitored client-driven local area network",
  "clauseValue": "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Romeo Juliett",
  "created": "2020-11-09T05:29:33Z"
}, {
  "id": 8,
  "label": "Capital Goods",
  "type": "Single Select",
  "active": true,
  "sfObject": "Account",
  "sfField": "matrices",
  "clauseLabel": "Polarised heuristic artificial intelligence",
  "clauseValue": "Curabitur convallis.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Alfa X-ray Bravo",
  "created": "2020-10-12T17:18:48Z"
}, {
  "id": 9,
  "label": "Consumer Non-Durables",
  "type": "Number",
  "active": true,
  "sfObject": "Contract",
  "sfField": "hardware",
  "clauseLabel": "Multi-layered non-volatile encryption",
  "clauseValue": "Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
  "clauseActive": true,
  "clauseObject": "Lead",
  "clauseField": "Alfa Quebec Sierra",
  "created": "2020-10-08T01:32:46Z"
}, {
  "id": 10,
  "label": "Basic Industries",
  "type": "Single Select",
  "active": true,
  "sfObject": "Lead",
  "sfField": "strategy",
  "clauseLabel": "Integrated methodical application",
  "clauseValue": "Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Lima Alfa",
  "created": "2020-10-16T06:41:42Z"
}, {
  "id": 11,
  "label": "Finance",
  "type": "Number",
  "active": true,
  "sfObject": "Lead",
  "sfField": "Fully-configurable",
  "clauseLabel": "Ergonomic solution-oriented conglomeration",
  "clauseValue": "Donec ut mauris eget massa tempor convallis.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Victor Quebec Bravo",
  "created": "2020-10-21T09:53:56Z"
}, {
  "id": 12,
  "label": "Technology",
  "type": "Single Select",
  "active": true,
  "sfObject": "Custom Obj 1",
  "sfField": "paradigm",
  "clauseLabel": "Integrated 24 hour alliance",
  "clauseValue": "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Juliett",
  "created": "2020-10-14T15:56:33Z"
}, {
  "id": 13,
  "label": "n/a",
  "type": "Boolean",
  "active": true,
  "sfObject": "Account",
  "sfField": "flexibility",
  "clauseLabel": "Virtual homogeneous system engine",
  "clauseValue": "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Zulu India Golf",
  "created": "2020-11-04T11:23:41Z"
}, {
  "id": 14,
  "label": "Finance",
  "type": "String",
  "active": false,
  "sfObject": "Opportunity",
  "sfField": "Reduced",
  "clauseLabel": "Triple-buffered homogeneous info-mediaries",
  "clauseValue": "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 2",
  "clauseField": "India X-ray Juliett",
  "created": "2020-10-19T20:10:46Z"
}, {
  "id": 15,
  "label": "Capital Goods",
  "type": "Boolean",
  "active": false,
  "sfObject": "Account",
  "sfField": "bottom-line",
  "clauseLabel": "Object-based national concept",
  "clauseValue": "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Victor",
  "created": "2020-10-28T01:21:45Z"
}, {
  "id": 16,
  "label": "Public Utilities",
  "type": "Boolean",
  "active": false,
  "sfObject": "Account",
  "sfField": "productivity",
  "clauseLabel": "Synchronised tertiary project",
  "clauseValue": "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.",
  "clauseActive": false,
  "clauseObject": "Lead",
  "clauseField": "India",
  "created": "2020-10-08T06:37:02Z"
}, {
  "id": 17,
  "label": "Finance",
  "type": "Multiselect",
  "active": true,
  "sfObject": "Contract",
  "sfField": "array",
  "clauseLabel": "Re-contextualized radical knowledge user",
  "clauseValue": "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
  "clauseActive": true,
  "clauseObject": "Opportunity",
  "clauseField": "Zulu",
  "created": "2020-10-06T20:24:44Z"
}, {
  "id": 18,
  "label": "Basic Industries",
  "type": "Multiselect",
  "active": true,
  "sfObject": "Lead",
  "sfField": "Enterprise-wide",
  "clauseLabel": "Integrated background installation",
  "clauseValue": "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
  "clauseActive": false,
  "clauseObject": "Contract",
  "clauseField": "Delta Uniform Whiskey",
  "created": "2020-10-18T21:04:47Z"
}, {
  "id": 19,
  "label": "Capital Goods",
  "type": "Boolean",
  "active": false,
  "sfObject": "Custom Obj 1",
  "sfField": "Fundamental",
  "clauseLabel": "Innovative human-resource groupware",
  "clauseValue": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.",
  "clauseActive": false,
  "clauseObject": "Opportunity",
  "clauseField": "Sierra Delta Charlie",
  "created": "2020-11-01T13:18:10Z"
}, {
  "id": 20,
  "label": "Health Care",
  "type": "Number",
  "active": false,
  "sfObject": "Custom Obj 2",
  "sfField": "bandwidth-monitored",
  "clauseLabel": "Face to face dedicated support",
  "clauseValue": "In sagittis dui vel nisl. Duis ac nibh.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Echo Oscar Whiskey",
  "created": "2020-10-12T03:08:13Z"
}, {
  "id": 21,
  "label": "Health Care",
  "type": "Number",
  "active": false,
  "sfObject": "Account",
  "sfField": "non-volatile",
  "clauseLabel": "Pre-emptive regional parallelism",
  "clauseValue": "Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum.",
  "clauseActive": true,
  "clauseObject": "Lead",
  "clauseField": "November Whiskey",
  "created": "2020-11-02T00:24:58Z"
}, {
  "id": 22,
  "label": "Finance",
  "type": "String",
  "active": false,
  "sfObject": "Lead",
  "sfField": "solution-oriented",
  "clauseLabel": "Persistent uniform task-force",
  "clauseValue": "Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Papa",
  "created": "2020-10-14T14:31:43Z"
}, {
  "id": 23,
  "label": "Technology",
  "type": "Number",
  "active": true,
  "sfObject": "Contract",
  "sfField": "access",
  "clauseLabel": "Switchable even-keeled intranet",
  "clauseValue": "Morbi a ipsum.",
  "clauseActive": true,
  "clauseObject": "Contract",
  "clauseField": "Bravo Sierra",
  "created": "2020-10-28T20:33:30Z"
}, {
  "id": 24,
  "label": "Technology",
  "type": "Single Select",
  "active": false,
  "sfObject": "Lead",
  "sfField": "neutral",
  "clauseLabel": "Secured bandwidth-monitored help-desk",
  "clauseValue": "Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Kilo Mike",
  "created": "2020-10-21T04:16:08Z"
}, {
  "id": 25,
  "label": "n/a",
  "type": "Number",
  "active": true,
  "sfObject": "Account",
  "sfField": "Reduced",
  "clauseLabel": "Realigned leading edge neural-net",
  "clauseValue": "Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "X-ray",
  "created": "2020-11-02T10:44:25Z"
}, {
  "id": 26,
  "label": "Health Care",
  "type": "Multiselect",
  "active": true,
  "sfObject": "Custom Obj 2",
  "sfField": "intranet",
  "clauseLabel": "Exclusive stable collaboration",
  "clauseValue": "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
  "clauseActive": true,
  "clauseObject": "Opportunity",
  "clauseField": "Charlie",
  "created": "2020-11-03T03:27:33Z"
}, {
  "id": 27,
  "label": "Transportation",
  "type": "Single Select",
  "active": true,
  "sfObject": "Opportunity",
  "sfField": "Team-oriented",
  "clauseLabel": "Reactive 5th generation support",
  "clauseValue": "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
  "clauseActive": true,
  "clauseObject": "Account",
  "clauseField": "Uniform",
  "created": "2020-11-03T17:32:20Z"
}, {
  "id": 28,
  "label": "Health Care",
  "type": "String",
  "active": false,
  "sfObject": "Custom Obj 2",
  "sfField": "emulation",
  "clauseLabel": "Programmable client-server circuit",
  "clauseValue": "Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "India",
  "created": "2020-10-19T17:23:34Z"
}, {
  "id": 29,
  "label": "n/a",
  "type": "String",
  "active": false,
  "sfObject": "Custom Obj 2",
  "sfField": "local",
  "clauseLabel": "Synergized directional adapter",
  "clauseValue": "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
  "clauseActive": false,
  "clauseObject": "Opportunity",
  "clauseField": "Whiskey Mike",
  "created": "2020-11-05T22:17:59Z"
}, {
  "id": 30,
  "label": "Health Care",
  "type": "String",
  "active": false,
  "sfObject": "Contract",
  "sfField": "multimedia",
  "clauseLabel": "Public-key encompassing application",
  "clauseValue": "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
  "clauseActive": false,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Oscar",
  "created": "2020-11-09T20:02:00Z"
}, {
  "id": 31,
  "label": "Miscellaneous",
  "type": "Multiselect",
  "active": false,
  "sfObject": "Opportunity",
  "sfField": "zero tolerance",
  "clauseLabel": "Synergized heuristic contingency",
  "clauseValue": "Pellentesque eget nunc.",
  "clauseActive": true,
  "clauseObject": "Contract",
  "clauseField": "Zulu Mike",
  "created": "2020-10-16T07:03:53Z"
}, {
  "id": 32,
  "label": "Energy",
  "type": "Number",
  "active": false,
  "sfObject": "Custom Obj 1",
  "sfField": "encryption",
  "clauseLabel": "Triple-buffered zero defect encryption",
  "clauseValue": "Pellentesque eget nunc.",
  "clauseActive": false,
  "clauseObject": "Contract",
  "clauseField": "Lima Kilo Quebec",
  "created": "2020-10-22T17:03:31Z"
}, {
  "id": 33,
  "label": "Consumer Durables",
  "type": "String",
  "active": false,
  "sfObject": "Opportunity",
  "sfField": "secured line",
  "clauseLabel": "Multi-tiered cohesive solution",
  "clauseValue": "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
  "clauseActive": false,
  "clauseObject": "Opportunity",
  "clauseField": "Tango",
  "created": "2020-10-08T19:36:16Z"
}, {
  "id": 34,
  "label": "Finance",
  "type": "Number",
  "active": false,
  "sfObject": "Contract",
  "sfField": "system engine",
  "clauseLabel": "Monitored directional encryption",
  "clauseValue": "In hac habitasse platea dictumst.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 1",
  "clauseField": "Kilo India",
  "created": "2020-10-20T21:06:38Z"
}, {
  "id": 35,
  "label": "Transportation",
  "type": "Boolean",
  "active": true,
  "sfObject": "Lead",
  "sfField": "impactful",
  "clauseLabel": "Fundamental modular instruction set",
  "clauseValue": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Charlie Quebec Bravo",
  "created": "2020-10-30T15:41:31Z"
}, {
  "id": 36,
  "label": "Public Utilities",
  "type": "Single Select",
  "active": false,
  "sfObject": "Lead",
  "sfField": "foreground",
  "clauseLabel": "Optional modular productivity",
  "clauseValue": "Integer a nibh. In quis justo.",
  "clauseActive": true,
  "clauseObject": "Account",
  "clauseField": "Bravo Charlie",
  "created": "2020-10-31T13:52:05Z"
}, {
  "id": 37,
  "label": "Finance",
  "type": "Multiselect",
  "active": false,
  "sfObject": "Lead",
  "sfField": "framework",
  "clauseLabel": "Grass-roots bi-directional knowledge user",
  "clauseValue": "Integer a nibh. In quis justo.",
  "clauseActive": true,
  "clauseObject": "Custom Obj 2",
  "clauseField": "Mike",
  "created": "2020-11-05T17:22:52Z"
}, {
  "id": 38,
  "label": "Consumer Services",
  "type": "Single Select",
  "active": true,
  "sfObject": "Lead",
  "sfField": "user-facing",
  "clauseLabel": "Diverse static capacity",
  "clauseValue": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Echo Kilo",
  "created": "2020-10-19T08:39:27Z"
}, {
  "id": 39,
  "label": "Consumer Services",
  "type": "Number",
  "active": true,
  "sfObject": "Contract",
  "sfField": "Multi-channelled",
  "clauseLabel": "Distributed scalable customer loyalty",
  "clauseValue": "Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla.",
  "clauseActive": true,
  "clauseObject": "Lead",
  "clauseField": "November Charlie",
  "created": "2020-10-07T16:40:15Z"
}, {
  "id": 40,
  "label": "Public Utilities",
  "type": "Multiselect",
  "active": true,
  "sfObject": "Contract",
  "sfField": "pricing structure",
  "clauseLabel": "Compatible didactic frame",
  "clauseValue": "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem. Sed sagittis.",
  "clauseActive": true,
  "clauseObject": "Lead",
  "clauseField": "Golf Yankee",
  "created": "2020-11-03T02:48:29Z"
}, {
  "id": 41,
  "label": "n/a",
  "type": "Multiselect",
  "active": false,
  "sfObject": "Account",
  "sfField": "Versatile",
  "clauseLabel": "Intuitive fresh-thinking info-mediaries",
  "clauseValue": "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
  "clauseActive": true,
  "clauseObject": "Lead",
  "clauseField": "Papa Yankee",
  "created": "2020-10-24T00:03:34Z"
}, {
  "id": 42,
  "label": "Health Care",
  "type": "Boolean",
  "active": false,
  "sfObject": "Custom Obj 2",
  "sfField": "system engine",
  "clauseLabel": "Intuitive local budgetary management",
  "clauseValue": "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Kilo Zulu",
  "created": "2020-10-24T20:05:33Z"
}, {
  "id": 43,
  "label": "n/a",
  "type": "Number",
  "active": true,
  "sfObject": "Contract",
  "sfField": "regional",
  "clauseLabel": "Multi-channelled executive benchmark",
  "clauseValue": "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
  "clauseActive": false,
  "clauseObject": "Opportunity",
  "clauseField": "Kilo",
  "created": "2020-10-29T07:05:33Z"
}, {
  "id": 44,
  "label": "n/a",
  "type": "Single Select",
  "active": false,
  "sfObject": "Custom Obj 2",
  "sfField": "info-mediaries",
  "clauseLabel": "Operative mission-critical knowledge user",
  "clauseValue": "Nullam sit amet turpis elementum ligula vehicula consequat.",
  "clauseActive": false,
  "clauseObject": "Opportunity",
  "clauseField": "Mike Uniform",
  "created": "2020-10-27T18:14:30Z"
}, {
  "id": 45,
  "label": "Finance",
  "type": "Single Select",
  "active": false,
  "sfObject": "Account",
  "sfField": "intangible",
  "clauseLabel": "Managed demand-driven system engine",
  "clauseValue": "Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh.",
  "clauseActive": false,
  "clauseObject": "Account",
  "clauseField": "Victor Delta Whiskey",
  "created": "2020-10-22T01:08:07Z"
}];

  export { mockData};